---
# Define the handlers for VPP
 
    #: start vpp service
    - name: start_vpp 
      service: name=vpp state=started

    #: restart vpp service
    - name: restart_vpp 
      service: name=vpp state=restarted

    #: stop vpp service
    - name: stop_vpp
      service: name=vpp state=stop
