---
# Role for VPP binaries from repository


# Removal of VPP and dependencies
 - name: Remove the vpp packages and dependencies
   include: vpp-uninstall.yml
   when: run_uninstall|default(false)

# Installation of VPP and dependencies
 - name: Remove the vpp packages and dependencies
   include: vpp-install.yml
   when: run_install|default(false)


