---
# Role for installing VPP binaries 

 - name: print current dir
   command: pwd

 - name: Add environment variable UBUNTU  in the .profile
   lineinfile: 
     dest: /home/{{ user }}/.profile 
     line: 'export UBUNTU={{ ubuntu_rel }}' 
     regexp: '^export UBUNTU='
     insertafter: 'EOF' 

 - name: Add environment variable UBUNTU_RELEASE  in the .profile
   lineinfile: 
     dest: /home/{{ user }}/.profile 
     line: 'export UBUNTU_RELEASE={{ ubuntu_ver }}' 
     regexp: '^export UBUNTU_RELEASE='
     insertafter: 'EOF' 

 - name: Clear the apt sources for fd.io
   file: path=/etc/apt/sources.list.d/99fd.io.list state=absent
   become: yes

 - name: Install the VPP binaries (update sources list)
   environment:
     UBUNTU: "{{ubuntu_rel}}"
     UBUNTU_RELEASE: "{{ubuntu_ver}}"
   become: yes
   shell: echo "deb [trusted=yes] https://nexus.fd.io/content/repositories/fd.io$UBUNTU_RELEASE.ubuntu.$UBUNTU.main/ ./" | sudo tee -a /etc/apt/sources.list.d/99fd.io.list

 - name:  apt update - update the cache
   environment:
     UBUNTU: "{{ubuntu_rel}}"
     UBUNTU_RELEASE: "{{ubuntu_ver}}"
   become: yes
   apt:
       update_cache: yes
   register: apt_result
   until: apt_result | success
   retries: 3
   delay: 1
   ignore_errors: yes

 - name: retry if needed using command apt-get update
   command: apt-get update
   become: yes
   when: apt_result|failed

 - name: Install the VPP binaries (install vpp )
   environment:
     UBUNTU: "{{ubuntu_rel}}"
     UBUNTU_RELEASE: "{{ubuntu_ver}}"
   become: yes
   apt:
     name: vpp 
     state: present

 - name: Install the VPP binaries (install vpp-dpdk-dkms)
   environment:
     UBUNTU: "{{ubuntu_rel}}"
     UBUNTU_RELEASE: "1701"
   become: yes
   apt:
     name: vpp-dpdk-dkms 
   register: vpp_installed

 - name: Start vpp service after install
   command: start vpp
   when: vpp_installed
   become: yes

 - name: Check vpp version
   command: vppctl show version
   become: yes
   register: installed_vpp_version

 - name: Print vpp version
   debug: msg="VPP version is {{ installed_vpp_version.stdout }} "
