---
# Install utilities like lshw

  - name: Install lshw utility
    when: ansible_os_family == 'Debian'
    become: yes
    apt: 
       state: present
       name: "{{item}}" 
    with_items:
        - lshw
